image: python:3.9-slim-buster

stages:
    - build
    - deploy

before_script:
    - pip install jupyter nbconvert

build_notebooks:
    stage: build
    script:
        - mkdir -p public
        - jupyter nbconvert --to html notebooks/*.ipynb --output-dir=public
    artifacts:
        paths:
            - public
        
pages:
    stage: deploy
    script:
        - echo "Deploying Pages"
    artifacts:
        paths:
            - public
    only:
        - master
